# Form implementation generated from reading ui file 'ui_files/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openGLWidget = GLViewWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(20, 40, 531, 381))
        self.openGLWidget.setObjectName("openGLWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 470, 151, 32))
        self.pushButton.setObjectName("pushButton")
        self.holePatternCombobox = QtWidgets.QComboBox(self.centralwidget)
        self.holePatternCombobox.setGeometry(QtCore.QRect(570, 50, 104, 26))
        self.holePatternCombobox.setObjectName("holePatternCombobox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(580, 30, 81, 16))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(560, 180, 251, 331))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.tableWidget.setFont(font)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setDefaultSectionSize(20)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(19)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 841, 24))
        self.menubar.setObjectName("menubar")
        self.menufiles = QtWidgets.QMenu(self.menubar)
        self.menufiles.setObjectName("menufiles")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionsave = QtGui.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionload = QtGui.QAction(MainWindow)
        self.actionload.setObjectName("actionload")
        self.actionexit = QtGui.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menufiles.addAction(self.actionsave)
        self.menufiles.addAction(self.actionload)
        self.menufiles.addAction(self.actionexit)
        self.menubar.addAction(self.menufiles.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Output STL file"))
        self.label.setText(_translate("MainWindow", "hole pattern"))
        self.menufiles.setTitle(_translate("MainWindow", "files"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionload.setText(_translate("MainWindow", "load"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
from pyqtgraph.opengl import GLViewWidget
